//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public DichVu()
        {
            this.ChiTietDichVuPhieuDatPhongs = new HashSet<ChiTietDichVuPhieuDatPhong>();
        }
    
        public string MaDV { get; set; }
        public string MaLoaiDV { get; set; }
        public string TenDV { get; set; }
        public double GiaTien { get; set; }
    
        public virtual ICollection<ChiTietDichVuPhieuDatPhong> ChiTietDichVuPhieuDatPhongs { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
    }
}
