//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDichVu
    {
        public LoaiDichVu()
        {
            this.DichVus = new HashSet<DichVu>();
        }
    
        public string MaLoaiDV { get; set; }
        public string TenLoaiDV { get; set; }
    
        public virtual ICollection<DichVu> DichVus { get; set; }
    }
}
