//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.PhieuDatPhongs = new HashSet<PhieuDatPhong>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string SDT { get; set; }
        public string NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string HinhAnh { get; set; }
        public string VaiTro { get; set; }
        public string Email { get; set; }
        public bool Phai { get; set; }
        public string MatKhau { get; set; }
        public string CCCD { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<PhieuDatPhong> PhieuDatPhongs { get; set; }
    }
}
