//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.ChiTietPhieuDatPhongs = new HashSet<ChiTietPhieuDatPhong>();
        }
    
        public string MaPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public string TinhTrang { get; set; }
        public int Tang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietPhieuDatPhong> ChiTietPhieuDatPhongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
