//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QL_KhachSanEntities : DbContext
    {
        public QL_KhachSanEntities()
            : base("name=QL_KhachSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDichVuPhieuDatPhong> ChiTietDichVuPhieuDatPhongs { get; set; }
        public DbSet<ChiTietPhieuDatPhong> ChiTietPhieuDatPhongs { get; set; }
        public DbSet<DichVu> DichVus { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhieuDatPhong> PhieuDatPhongs { get; set; }
        public DbSet<Phong> Phongs { get; set; }
        public DbSet<TienNghiPhong> TienNghiPhongs { get; set; }
        public DbSet<ViewDV> ViewDVs { get; set; }
    
        public virtual int InsertChiTietDVPhieuDatPhong(string maPDP, string maPhong, string maDV, Nullable<int> soLuongDichVu)
        {
            var maPDPParameter = maPDP != null ?
                new ObjectParameter("MaPDP", maPDP) :
                new ObjectParameter("MaPDP", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            var soLuongDichVuParameter = soLuongDichVu.HasValue ?
                new ObjectParameter("SoLuongDichVu", soLuongDichVu) :
                new ObjectParameter("SoLuongDichVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertChiTietDVPhieuDatPhong", maPDPParameter, maPhongParameter, maDVParameter, soLuongDichVuParameter);
        }
    
        public virtual int InsertChiTietPhieuDatPhong(string maPDP, string maPhong, Nullable<System.DateTime> ngayDat, Nullable<System.DateTime> ngayKetThuc, Nullable<System.TimeSpan> gioDat, Nullable<System.TimeSpan> gioKetThuc)
        {
            var maPDPParameter = maPDP != null ?
                new ObjectParameter("MaPDP", maPDP) :
                new ObjectParameter("MaPDP", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var ngayDatParameter = ngayDat.HasValue ?
                new ObjectParameter("NgayDat", ngayDat) :
                new ObjectParameter("NgayDat", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var gioDatParameter = gioDat.HasValue ?
                new ObjectParameter("GioDat", gioDat) :
                new ObjectParameter("GioDat", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertChiTietPhieuDatPhong", maPDPParameter, maPhongParameter, ngayDatParameter, ngayKetThucParameter, gioDatParameter, gioKetThucParameter);
        }
    
        public virtual int InsertDichVu(string maLoaiDV, string tenDV, Nullable<double> giaTien)
        {
            var maLoaiDVParameter = maLoaiDV != null ?
                new ObjectParameter("MaLoaiDV", maLoaiDV) :
                new ObjectParameter("MaLoaiDV", typeof(string));
    
            var tenDVParameter = tenDV != null ?
                new ObjectParameter("TenDV", tenDV) :
                new ObjectParameter("TenDV", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertDichVu", maLoaiDVParameter, tenDVParameter, giaTienParameter);
        }
    
        public virtual int InsertHoaDon(string maPDP, Nullable<double> tongGiaTri)
        {
            var maPDPParameter = maPDP != null ?
                new ObjectParameter("MaPDP", maPDP) :
                new ObjectParameter("MaPDP", typeof(string));
    
            var tongGiaTriParameter = tongGiaTri.HasValue ?
                new ObjectParameter("TongGiaTri", tongGiaTri) :
                new ObjectParameter("TongGiaTri", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHoaDon", maPDPParameter, tongGiaTriParameter);
        }
    
        public virtual int InsertKhachHang(string tenKH, string sDT, string ngaySinh, string diaChi, string phai, string maCMT, string quocTich)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh != null ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var phaiParameter = phai != null ?
                new ObjectParameter("Phai", phai) :
                new ObjectParameter("Phai", typeof(string));
    
            var maCMTParameter = maCMT != null ?
                new ObjectParameter("MaCMT", maCMT) :
                new ObjectParameter("MaCMT", typeof(string));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertKhachHang", tenKHParameter, sDTParameter, ngaySinhParameter, diaChiParameter, phaiParameter, maCMTParameter, quocTichParameter);
        }
    
        public virtual int InsertLoaiDichVu(string tenLoaiDichVu)
        {
            var tenLoaiDichVuParameter = tenLoaiDichVu != null ?
                new ObjectParameter("TenLoaiDichVu", tenLoaiDichVu) :
                new ObjectParameter("TenLoaiDichVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLoaiDichVu", tenLoaiDichVuParameter);
        }
    
        public virtual int InsertLoaiPhong(string tenLoaiPhong, Nullable<double> giaTheoGio, Nullable<double> giaTheoNgay)
        {
            var tenLoaiPhongParameter = tenLoaiPhong != null ?
                new ObjectParameter("TenLoaiPhong", tenLoaiPhong) :
                new ObjectParameter("TenLoaiPhong", typeof(string));
    
            var giaTheoGioParameter = giaTheoGio.HasValue ?
                new ObjectParameter("GiaTheoGio", giaTheoGio) :
                new ObjectParameter("GiaTheoGio", typeof(double));
    
            var giaTheoNgayParameter = giaTheoNgay.HasValue ?
                new ObjectParameter("GiaTheoNgay", giaTheoNgay) :
                new ObjectParameter("GiaTheoNgay", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLoaiPhong", tenLoaiPhongParameter, giaTheoGioParameter, giaTheoNgayParameter);
        }
    
        public virtual int InsertNhanVien(string tenNV, string sDT, string ngaySinh, string diaChi, string hinhAnh, string vaiTro, string email, string phai, string matKhau, string cCCD)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh != null ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var vaiTroParameter = vaiTro != null ?
                new ObjectParameter("VaiTro", vaiTro) :
                new ObjectParameter("VaiTro", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phaiParameter = phai != null ?
                new ObjectParameter("Phai", phai) :
                new ObjectParameter("Phai", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertNhanVien", tenNVParameter, sDTParameter, ngaySinhParameter, diaChiParameter, hinhAnhParameter, vaiTroParameter, emailParameter, phaiParameter, matKhauParameter, cCCDParameter);
        }
    
        public virtual int InsertPhieuDatPhong(string maKH, string maNV, Nullable<int> soNguoi, string tinhTrang)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var soNguoiParameter = soNguoi.HasValue ?
                new ObjectParameter("SoNguoi", soNguoi) :
                new ObjectParameter("SoNguoi", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPhieuDatPhong", maKHParameter, maNVParameter, soNguoiParameter, tinhTrangParameter);
        }
    
        public virtual int InsertPhong(string maLoaiPhong, Nullable<int> tang)
        {
            var maLoaiPhongParameter = maLoaiPhong != null ?
                new ObjectParameter("MaLoaiPhong", maLoaiPhong) :
                new ObjectParameter("MaLoaiPhong", typeof(string));
    
            var tangParameter = tang.HasValue ?
                new ObjectParameter("Tang", tang) :
                new ObjectParameter("Tang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPhong", maLoaiPhongParameter, tangParameter);
        }
    
        public virtual int InsertTienNghiPhong(string maLoaiPhong, string ten, Nullable<int> sL)
        {
            var maLoaiPhongParameter = maLoaiPhong != null ?
                new ObjectParameter("MaLoaiPhong", maLoaiPhong) :
                new ObjectParameter("MaLoaiPhong", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTienNghiPhong", maLoaiPhongParameter, tenParameter, sLParameter);
        }
    }
}
