//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDV
    {
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public double GiaTien { get; set; }
        public string TenLoaiDV { get; set; }
    }
}
