//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuDatPhong
    {
        public ChiTietPhieuDatPhong()
        {
            this.ChiTietDichVuPhieuDatPhongs = new HashSet<ChiTietDichVuPhieuDatPhong>();
        }
    
        public string MaPDP { get; set; }
        public string MaPhong { get; set; }
        public double TongGiaTri { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public System.TimeSpan GioDat { get; set; }
        public System.TimeSpan GioKetThuc { get; set; }
    
        public virtual ICollection<ChiTietDichVuPhieuDatPhong> ChiTietDichVuPhieuDatPhongs { get; set; }
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
