//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string MaPDP { get; set; }
        public double TongGiaTri { get; set; }
        public System.DateTime NgayInHD { get; set; }
        public string DanhGia { get; set; }
    
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
    }
}
