//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHoaDon
    {
        public string MaHD { get; set; }
        public double TongGiaTri { get; set; }
        public System.DateTime NgayInHD { get; set; }
        public string MaPDP { get; set; }
        public string MaPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public double GiaTheoGio { get; set; }
        public double GiaTheoNgay { get; set; }
        public string TenDV { get; set; }
        public string MaDV { get; set; }
        public int SoLuongDV { get; set; }
        public double GiaTien { get; set; }
        public double ThanhTien { get; set; }
        public int SoNguoi { get; set; }
    }
}
